version: '3.8'
services:
  db:
    image: mysql:8.0.37
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
      
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "8080:8080"  # Expose Spring Boot on port 8080
    volumes:
      - ../../api/src:/app/src  # Mount the source code for live changes
      - ../../api/target:/app/target  # Mount the target directory (optional)
      - ../../api/pom.xml:/app/pom.xml
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # Optional: activate development profile
    command: "mvn spring-boot:run"

  webapp:
    build:
      context: ../../webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "3000:3000"
    volumes:
      - ../../webapp:/app
      - /app/node_modules # separate volume for node_modules to avoid unnecessary npm installs
    environment:
      NODE_ENV: development
    command: "npm run dev"

