version: '3.8'
services:
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ../../api:/api
    command: python manage.py runserver 0.0.0.0:8000

  webapp:
    build:
      context: ../../webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "4200:4200"
    volumes:
      - ../../webapp:/app
      - /app/node_modules # separate volume for node_modules to avoid unnecessary npm installs
    command: ng serve --host 0.0.0.0 --port 4200