services:
  db:
    image: postgres:16.4
    container_name: db
    volumes:
      - ./data:/var/lib/pgsql
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../../api:/api
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  webapp:
    build:
      context: ../../webapp
      dockerfile: Dockerfile
      target: dev   # Use the 'dev' stage for local development
    container_name: webapp
    ports:
      - "3000:3000"
    volumes:
      - ../../webapp:/app
      - /app/node_modules # separate volume for node_modules to avoid unnecessary npm installs
    command: "npm run dev"

