version: '3.8'
services:
  db:
    image: mysql:8.0.37
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../../api:/api
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  # webapp:
  #   build:
  #     context: ../../webapp
  #     dockerfile: Dockerfile
  #   container_name: webapp
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ../../webapp:/app
  #     - /app/node_modules # separate volume for node_modules to avoid unnecessary npm installs
  #   command: ng serve --host 0.0.0.0 --port 4200

