apiVersion: v1
kind: Service
metadata:
    name: api
spec:
    selector:
        app: api
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: api
                  image: api:latest
                  imagePullPolicy: Never # for local development
                  command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
                  envFrom:
                      - secretRef:
                            name: api-secrets
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                  workingDir: /api
