---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arc
  region: eu-west-2
  tags:
    project: arc

nodeGroups:
  - name: worker-node
    instanceType: t3.medium # 2vCPU, 4GiB RAM, 5Gbps network, $0.0472 per Hour
    desiredCapacity: 1